### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by y26805** [chakki-works/chakin#14]
When trying to run `chakin.download()`, I encountered the following error:

```
Traceback (most recent call last):                                                                                   
  File "<stdin>", line 1, in <module>                                                                            
  File "/Users/s/.text-segmentation/lib/python3.6/site-packages/chakin/downloader.py", line 41, in download   
    path, _ = urlretrieve(url, save_path, reporthook=dlProgress)                                                     
  File "/Users/s/.pyenv/versions/3.6.5/lib/python3.6/urllib/request.py", line 248, in urlretrieve              
    with contextlib.closing(urlopen(url, data)) as fp:                                                                                        
  File "/Users/s/.pyenv/versions/3.6.5/lib/python3.6/urllib/request.py", line 223, in urlopen                   
    return opener.open(url, data, timeout)                                                                           
  File "/Users/s/.pyenv/versions/3.6.5/lib/python3.6/urllib/request.py", line 532, in open                    
    response = meth(req, response)                                                                                  
  File "/Users/s/.pyenv/versions/3.6.5/lib/python3.6/urllib/request.py", line 642, in http_response            
    'http', request, response, code, msg, hdrs)                                                                     
  File "/Users/s/.pyenv/versions/3.6.5/lib/python3.6/urllib/request.py", line 570, in error                    
    return self._call_chain(*args)                                                                                   
  File "/Users/s/.pyenv/versions/3.6.5/lib/python3.6/urllib/request.py", line 504, in _call_chain               
    result = func(*args)                                                                                             
  File "/Users/s/.pyenv/versions/3.6.5/lib/python3.6/urllib/request.py", line 650, in http_error_default        
    raise HTTPError(req.full_url, code, msg, hdrs, fp)                                                                
urllib.error.HTTPError: HTTP Error 403: Forbidden 
```

I am running Python 3.6.5.

**Comment by icoxfog417** [comment]
Thank you for reporting the error. Could you tell us what kinds of embedding you downloaded?

**Comment by y26805** [comment]
I tried to download "fastText(en)". It seems other sources work fine except for this one.

**Comment by icoxfog417** [comment]
Thanks! Pretrained word vectors of fastText seem to be changed. So links should be changed.

[Word vectors for 157 languages](https://fasttext.cc/docs/en/crawl-vectors.html)

**Comment by icoxfog417** [comment]
Done 
fef88a1f91a9306fd591a66f039e18ca917fa09c
